import { prisma } from '../src/lib/prisma';
import { faker } from '@faker-js/faker';
import { Prisma } from '../generated/prisma';
import { STATUSES } from '../src/lib/constants';

/**
 * Seed script — populate the database with 10,000 realistic leads.
 *
 * Run with: npx prisma db seed
 *
 * Design notes:
 * - website is the first two significant words of the company + a faker TLD
 *   (domainSuffix); email is first.last on that SAME domain, so website === email.
 * - emails are deduped via a Set: a numeric suffix is added ONLY on an actual
 *   collision, so the vast majority stay clean (email is @unique).
 * - statuses come from faker.helpers.arrayElement, so all four appear in
 *   roughly equal proportion (~25% each).
 * - createdAt: faker.date.recent({ days: 90 }) — uniform over the last 90 days.
 * - Idempotent: only seeds when the table is empty (skips otherwise).
 */

const TOTAL = 10_000;
const BATCH = 500;

const CONNECTORS = new Set(['and', '&']);

// Domain from the first two significant words of the company, e.g.
// "Kihn, Dooley and Dibbert" -> "kihndooley.com".
const toDomain = (company: string) => {
  const words = company
    .toLowerCase()
    .split(/[^a-z0-9]+/)
    .filter((w) => w && !CONNECTORS.has(w));
  return `${words.slice(0, 2).join('') || 'company'}.${faker.internet.domainSuffix()}`;
};

const existingEmails = new Set<string>();

/** faker email on the company domain, with a numeric suffix added only on collision. */
function uniqueEmail(firstName: string, lastName: string, domain: string): string {
  const [local, host] = faker.internet
    .email({ firstName, lastName, provider: domain, allowSpecialCharacters: false })
    .toLowerCase()
    .split('@');
  let email = `${local}@${host}`;
  for (let n = 2; existingEmails.has(email); n++) email = `${local}${n}@${host}`;
  existingEmails.add(email);
  return email;
}

/** Build a single lead. Every field is generated by faker except the domain,
 *  which is derived from the company so that website === email domain. */
function makeLead() {
  const firstName = faker.person.firstName();
  const lastName = faker.person.lastName();
  const company = faker.company.name();
  const domain = toDomain(company);

  return {
    name: `${firstName} ${lastName}`,
    company,
    website: domain,
    email: uniqueEmail(firstName, lastName, domain),
    status: faker.helpers.arrayElement(STATUSES),
    score: faker.number.int({ max: 100 }),
    enrichment: null,
    createdAt: faker.date.recent({ days: 90 }),
  };
}

/** Generate `size` leads and insert them via the given transaction client. */
async function seedBatch(tx: Prisma.TransactionClient, size = BATCH) {
  const leads = Array.from({ length: size }, () => makeLead());
  await tx.lead.createMany({ data: leads });
}

async function main() {
  const existing = await prisma.lead.count();
  if (existing > 0) {
    console.log(`DB already has ${existing} leads — skipping seed.`);
    return;
  }

  console.log(`Seeding ${TOTAL.toLocaleString()} leads...`);

  // Insert all batches in one transaction: a mid-run failure rolls back
  // instead of leaving a partially-seeded table.
  await prisma.$transaction(
    async (tx) => {
      for (let seeded = 0; seeded < TOTAL; seeded += BATCH) {
        await seedBatch(tx, Math.min(BATCH, TOTAL - seeded));
      }
    },
    { timeout: 60_000 },
  );

  console.log('Done.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
